require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '13.0' # iOS 최소 버전 설정 (필요에 따라 '18.0'도 가능)

use_modular_headers! # 모든 의존성을 모듈화된 헤더로 설정

target 'FitSync' do
  # React Native 기본 Pods 설정
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true # Hermes 활성화
  )

  target 'FitSyncTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(installer)
  end
end